<input type="file" id="ohcrud-file" multiple style="display: none;" />
<div class="alert hidden"></div>
<form id="ohcrud-editor">
    <input type="hidden" id="ohcrud-page-url" name="ohcrud-page-url" value="{{CMS:PATH}}" />
    <input type="hidden" id="ohcrud-themes" name="ohcrud-themes" value="{{CMS:THEMES}}" />
    <input type="hidden" id="ohcrud-page-current-theme" name="ohcrud-page-current-theme" value="{{CMS:THEME}}" />
    <input type="hidden" id="ohcrud-page-current-layout" name="ohcrud-page-current-layout" value="{{CMS:LAYOUT}}" />

    <div class="ohcrud-100">
        <div class="ohcrud-50">
            <input type="text" id="ohcrud-page-title" name="ohcrud-page-text" value="{{CMS:TITLE}}" />
        </div>
        <div class="ohcrud-25 padding-left">
            <select name="ohcrud-page-theme" id="ohcrud-page-theme"></select>
        </div>
        <div class="ohcrud-25 padding-left">
            <select name="ohcrud-page-layout" id="ohcrud-page-layout"></select>
        </div>
    </div>

    <textarea id="ohcrud-editor-text" name="ohcrud-editor-text">{{CMS:CONTENT-TEXT}}</textarea>
    <a class="btn btn-primary" id="ohcrud-editor-save">Save</a>
    <a class="btn btn-secondary" href="{{CMS:PATH}}">Cancel</a>
</form>