version: '3'
services:
  web:
    image: nginx:latest
    environment:
      - NGINX_HOST=ohcrud.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./private/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/cert.pem:/ssl/cert.pem
      - ./private/key.pem:/ssl/key.pem
      - ./public:/app
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: ./private/PHP.Dockerfile
    volumes:
      - ./public:/app
  composer_installation:
    image: composer
    volumes:
      - ./public:/app
    command: composer install --no-interaction --no-plugins --no-scripts --prefer-dist
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'ohcrud'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'ohcrud'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}
