<?php
    if (isset($_SESSION['User']) == false) {
        print("<a href=\"/login/?redirect=$path?action=edit\"><img src=\"/assets/images/ICON_EDIT.png\" id=\"OhCRUD_Page_Button_Action_Edit\" /></a>");
    } else {
        print("<a href=\"$path?action=edit\"><img src=\"/assets/images/ICON_EDIT.png\" id=\"OhCRUD_Page_Button_Action_Edit\" /></a>");
    }
?>

<div class="center-vh">
    <h1>Oh CRUD! You just got 404'd.</h1>
    <p>The page you requested at: <b><?= $path ?></b> could not be found.</p>
    <p>Use your browser's <b>Back</b> button to navigate to the page you have previously come from, or you could edit this page by pressing the edit button.</p>
    <br/>
    <a href="/"><button>HOME</button></a>
</div>