<?php
    $this->theme = 'login.php';
?>

<div class="col col-30 page center-vh">

    <form id="OhCRUD_Login" name="OhCRUD_Login">
        <h2>Please sign in</h2>
        <br>
        <div class="alert hidden"></div>
        <input type="text" placeholder="Username" id="OhCRUD_Login_Username" name="OhCRUD_Username">
        <input type="password" placeholder="Password" id="OhCRUD_Login_Password" name="OhCRUD_Password">
        <input type="hidden" id="OhCRUD_Login_Redirect" name="OhCRUD_Login_Redirect" value="<?php print($_REQUEST['redirect'] ?? ''); ?>">
        <br>
        <button type="button" id="OhCRUD_Login_Button">LOGIN</button>
    </form>

</div>

