<?php
    $content->theme = 'default';
    $content->layout = 'plain';
?>
<h1>This page is hard coded</p>

<p>It's been six hours. Dreams move one... one-hundredth the speed of reality, and dog time is one-seventh human time. So y'know, every day here is like a minute. It's like Inception, Morty, so if it's confusing and stupid, then so is everyone's favorite movie. Nothing you do matters, your existence is a lie! It's fine, everythings is fine. theres an infinite number of realities Morty, and in a few dozens of those i got lucky and turned everything back to normal. Nice, Mrs Pancakes. Real nice.</p>

<p>I don't know man, Italy, Greece, Argentina... I mean, why would a poptart want to live inside a toaster, Rick? I mean, that would be like the scariest place for them to live. You know what I mean? I dunno, some people would pay top dollar for that kind of breakthrough. Cool. Just stay in the driveway; the kill-bots are live, and I took you off the whitelist.</p>

<?php
    print(uniqid());
?>