<?php
	$this->title = 'OhCrud! Documentation';
?>

<div class="row">
	<div class="col-md-3">
		<nav role="navigation" class="navbar navbar-default navbar-fixed-side">
			<ul class="nav">
				<li><a href="#section1">Introduction</a></li>
				<li><a href="#section2">Getting Started</a>
					<ul class="nav">
						<li><a href="#section2_1">Installation</a></li>
						<li><a href="#section2_2">Configuration</a></li>
						<li><a href="#section2_3">Directory Structure</a></li>
					</ul>
				</li>
				<li><a href="#section3">The Basics</a>
					<ul class="nav">
						<li><a href="#section3_1">Core Object</a></li>
						<li><a href="#section3_2">Database Object</a></li>
						<li><a href="#section3_3">Router Object</a></li>
						<li><a href="#section3_4">Users Object</a></li>
					</ul>
				</li>
				<li><a href="#section4">Errors &amp; Logging</a></li>
				<li><a href="#section5">Command Line Interface</a></li>
			</ul>
		</nav >
	</div>
	<div class="col-md-9">

		<section id="section1">

			<div class="row">
				<div class="col-md-12 left-align">
					<h1 class="cl-black">Introduction</h1>
					<p>OhCrud is a PHP micro framework that helps you quickly write simple yet powerful applications and create APIs. At its core, it provides the basic <u>C</u>reate <u>R</u>ead <u>U</u>pdate <u>D</u>elete methods to interact with MySQL or SQLITE.</p>

					<blockquote>
						<p>Ninety percent of everything is crud.</p>
						<footer>Theodore Sturgeon</footer>
					</blockquote>

					<p>OhCrud uses composer and fully supports PSR-4 autoloading so you can reference your classes using the name spaces, You can easily define API or HTML endpoints and map incomming requests to your classes to handle, or you can use a catch all <mark>__OHCRUD_DEFAULT_PATH_HANDLER__</mark> to catch all the other requests.</p>

					<p>Framework comes with a secure users and permissions handling, you can define per method permissions for all your API endpoints.</p>

					<p>OhCrud uses <a href="https://github.com/Seldaek/monolog">Monolog</a> liberary to handle logs, all PDO exceptions are automatically logged into the designated log file in a well formated way.</p>

					<p>While I belive any programming language that comes with fulctions like <i>money_format</i>, or <i>ucwords</i> and so on... right out of the box is CRUD, my goal is to make things less shitty with my framework, but as a rule still contains ninety percent crud!</p>

				</div>
			</div>

		</section>
		<div class="spacer"></div>
		<!-- -------------------------------------------------------------------------------- -->

		<section id="section2">

			<div class="row">
				<div class="col-md-12 left-align">
					<h1 class="cl-black">Getting Started</h1>

					<p>The OhCrud framework has a few system requirements and you can run it on a Raspberry Pi 1 with SQLITE database, you will need to make sure your server meets the following requirements:</p>
					<ul>
						<li>PHP >= 5.6.0 (PHP 7 Recommended)</li>
						<li>PDO PHP Extension</li>
						<li>Mbstring PHP Extension</li>
						<li>PHP Curl Extension</li>
						<li>PHP SQLITE 3 (if using SQLITE for your database)</li>
					</ul>
					<div class="spacer"></div>

					<section id="section2_1">
						<h2 class="cl-black">Installation</h2>

						<p>OhCrud utilizes <a href="https://getcomposer.org/">Composer</a> to manage its dependencies. So, before using OhCrud, make sure you have Composer installed on your machine.</p>

						<p>To install OhCrud, first create a directory for your project in your webserver's root directory:</p>
<pre>
mkdir /var/www/OhCrud
</pre>

						<p>Then run the following commands:</p>
<pre>
git clone https://github.com/fellowgeek/OhCrud.git /var/www/OhCrud
rm -rf /var/www/OhCrud/.git
composer update
composer dump-autoload
</pre>

						<p>After all the files are copied in place you need to configure your webserver to redirect all the traffic from the missing paths to go to <mark>index.php</mark>, you can achieve this for Apache and Nginx using the configuration below:</p>

						<h3>Apache configuration</h3>
						<p>Make sure apache has the <mark>mod_rewrite</mark> enabled, there is a <mark>.htaccess</mark> file included in OhCrud package that should take care of everything for you but if you need to make one make sure it looks like this:</p>
<pre>
&lt;IfModule mod_rewrite.c&gt;
	RewriteEngine On
	RewriteBase /
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^.+$ index.php [QSA,L]

	RewriteRule ^/?logs/app\.log$ - [F,L]
	RewriteRule ^/?assets/db/data\.db$ - [F,L]
&lt;/IfModule&gt;
</pre>

						<p>Make sure your Apache virtual host is configured with the AllowOverride option so that the .htaccess rewrite rules can be used:</p>
<pre>
AllowOverride All
</pre>

						<h3>Nginx configuration</h3>
						<p>This is an example Nginx virtual host configuration for the domain example.com. It listens for inbound HTTP connections on port 80.</p>
						<p>You should update the <mark>server_name</mark>, <mark>error_log</mark>, <mark>access_log</mark>, and <mark>root</mark> directives with your own values. The root directive is the path to your application’s root directory.</p>

<pre>
server {
    listen 80;
    index index.php index.html index.htm;
    error_log /path/to/example.error.log;
    access_log /path/to/example.access.log;
    root /path/to/ohcrud;
    server_name example.com;

    location / {
	try_files $uri $uri/ @rewrite;
    }

    location @rewrite {
        rewrite ^.+$ /index.php;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }

    location ~ /(logs|assets/db) {
	deny all;
    }
}
</pre>

					</section>
					<div class="spacer"></div>

					<section id="section2_2">
						<h2 class="cl-black">Configuration</h2>

						<p>Use the table below to define the following settings constants in the <mark><span class="monospace">settings.php</span></mark> file that should be placed at the application's root directory. A <mark><span class="monospace">settings.sample.php</span></mark> file is provided as a starting point.</p>

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Setting</th>
                                    <th>Type</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="monospace">__SELF__</td>
                                    <td>String</td>
                                    <td>Same as <mark><span class="monospace">$_SERVER['DOCUMENT_ROOT']</span></mark>, contains the path to application's root folder.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__SITE__</td>
                                    <td>String</td>
                                    <td>Enter yout applications domain here i.e. <mark>example.com</mark></td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_DEBUG_MODE__</td>
                                    <td>Boolean</td>
                                    <td>If this is enabled, every OhCrud response will contain a <mark><span class="monospace">runtime</span></mark> and <mark><span class="monospace">SQL</span></mark> property if applicaple. This hsould be set to <mark><span class="monospace">false</span></mark> for production.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_DEBUG_EXPANDED_LEVEL__</td>
                                    <td>Integer</td>
                                    <td>This sets the initally expanded levels in the output of the <mark><span class="monospace">debug()</span></mark> method.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_LOG_FILE__</td>
                                    <td>String</td>
                                    <td>Path to the defualt log file, initally set to <mark><span class="monospace">/logs/app.log</span></mark></td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_SECRET__</td>
                                    <td>String</td>
                                    <td>Secret string used to generate passwords, you must change this to a random string for each project.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_SESSION_LIFETIME__</td>
                                    <td>Integer</td>
                                    <td>Application session cookie lifetime in seconds, defualt 3600 seconds.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_DB_STAMP__</td>
                                    <td>Boolean</td>
                                    <td>This will determione if OhCrud should add CDATE (create date), MDATE (midified date), CUSER (created by user id), MUSER (modified by user id) columns to every table.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_DB_CONFIG__</td>
                                    <td>Serialize Array</td>
                                    <td>Database settings for SQLITE or MYSQL should be entered here in the form of a serialized array.<br/>
										<div class="alert alert-danger">If you are using a SQLITE database, it is strongly recommended that you move the databse file outside of your web application directory.</div>
									</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_ENDPOINTS__</td>
                                    <td>Serialize Array</td>
                                    <td>API or HTML endpoints should be entered here in the form of a serialized array. You can map any arbitary URL path to a OhCrud or OhCrud compatible class to handle.</td>
                                </tr>
                                <tr>
                                    <td class="monospace">__OHCRUD_DEFAULT_PATH_HANDLER__</td>
                                    <td>String</td>
                                    <td>Use this setting to map any URL path that is not handled by the <mark><span class="monospace">__OHCRUD_DEFAULT_PATH_HANDLER__</span></mark>. This needs to be a OhCrud or OhCrud compatible classs. This is usefull if you have a content managment class to handle all the web pages.</td>
                                </tr>
                            </tbody>
                        </table>

					</section>
					<div class="spacer"></div>

					<section id="section2_3">
						<h2 class="cl-black">Directory Structure</h2>
					</section>

					<p>OhCrud utilizes <a href="https://getcomposer.org/">Composer</a> to manage its dependencies, all classes should be <a href="http://www.php-fig.org/psr/psr-4/">PSR-4</a> compliant to work with autoloading.</p>
					<p>Below you can see a breakdown of the OhCrud folders in alphabetical order.</p>

					<table class="table table-striped">
						<thead>
							<tr>
								<th>Directory</th>
								<th>Description</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="monospace">/app/</td>
								<td>The app directory, as you might expect, contains the core code of your application. We'll explore this directory in more detail below; however, almost all of the classes in your application will be in this directory.</td>
							</tr>
							<tr>
								<td class="monospace">/app/controllers/</td>
								<td>By default, this directory is namespaced under <mark>\App\Controllers</mark> and is autoloaded by Composer using the PSR-4 autoloading standard. Ideally your controller classes should exists under this directory.</td>
							</tr>
							<tr>
								<td class="monospace">/app/models/</td>
								<td>By default, this directory is namespaced under <mark>\App\Models</mark> and is autoloaded by Composer using the PSR-4 autoloading standard. Ideally your model classes should exists under this directory.</td>
							</tr>
							<tr>
								<td class="monospace">/app/views/</td>
								<td>This directory is for your application views.</td>
							</tr>
							<tr>
								<td class="monospace">/assets/css/</td>
								<td>CSS assets are located here, by default OhCrud comes with boostrap framework.</td>
							</tr>
							<tr>
								<td class="monospace">/assets/db/</td>
								<td>We used this directory to include a default SQLITE databse file.</td>
							</tr>
							<tr>
								<td class="monospace">/assets/fonts/</td>
								<td>Font assets are located here.</td>
							</tr>
							<tr>
								<td class="monospace">/assets/images/</td>
								<td>Image assets including the awesome OhCrud logo are located here.</td>
							</tr>
							<tr>
								<td class="monospace">/assets/js/</td>
								<td>Javascript assets are located here, by default OhCrud includes a copy of jQuery.</td>
							</tr>
							<tr>
								<td class="monospace">/logs/</td>
								<td>This is the defualt applicstion logs directory.</td>
							</tr>
							<tr>
								<td class="monospace">/OhCrud/</td>
								<td>This directory contains the OhCrud framework which consists of <mark>Core.php</mark>, <mark>DB.php</mark>, <mark>Router.php</mark>, and <mark>Users.php</mark>. We will discuss these files in detail in <a href="#section3">The Basics</a> section of this documentaion.</td>
							</tr>
							<tr>
								<td class="monospace">/vendor/</td>
								<td>The vendor directory contains your Composer dependencies.</td>
							</tr>
							<tr>
								<td class="monospace">/composer.json</td>
								<td>This file describes the dependencies of your project and may contain other metadata as well. You may add other classes you wish to include in autoloading under psr-4 key.</td>
							</tr>
							<tr>
								<td class="monospace">/index.php</td>
								<td>OhCrud index file, all web, API, and console requests will hit this file first.</td>
							</tr>
							<tr>
								<td class="monospace">/settings.php</td>
								<td>OhCrud settings are defined here. You should use the <mark>settings.sample.php</mark> to generate this.</td>
							</tr>
						</tbody>
					</table>

				</div>
			</div>

		</section>
		<div class="spacer"></div>
		<!-- -------------------------------------------------------------------------------- -->

		<section id="section3">

			<div class="row">
				<div class="col-md-12 left-align">
					<h2 class="cl-black">The Basics</h2>

						<p>All OhCrud classes inherit from the Core class. Ideally all of your models and controllers should do the same. If a class needs databse functions should inherit from the DB class, which itself inherits from Core.</p>
						<p>API and WEB endpoints are handled by the Router class, the Router checks if user has the correct permissions to access the end point and Routes the request to the correct class to handle.</p>
						<p>OhCrud uses the Users class to authenticate users and check permissions, when <mark>__OHCRUD_DEBUG_MODE__</mark> set to <mark>TRUE</mark> if the Users table does not exists, OhCrud will auto create the table and insert a default admin user into it.</p>

						<h3>OhCrud default username and password</h3>
<pre>
Username : admin
Password : admin
</pre>

					<div class="spacer"></div>

					<section id="section3_1">
						<h2 class="cl-black">Core Object</h2>

						<p>Every class in OhCrud inherits from the Core object, This class is responsible for setting the output type and http headers and performing tasks like logging, errors handling, remote requests, and debug.</p>

						<h3>Properties</h3>
							<table class="table table-striped">
								<thead>
									<tr>
										<th>Property</th>
										<th>Type</th>
										<th>Description</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td class="monospace">data</td>
										<td>Array</td>
										<td>This property holds results of a remote request or database query or any data.</td>
									</tr>
									<tr>
										<td class="monospace">errors</td>
										<td>Array</td>
										<td>If any errors occur it will be included in this element.</td>
									</tr>
									<tr>
										<td class="monospace">success</td>
										<td>Boolean</td>
										<td>This is set to <mark>TRUE</mark> if operation was successfull or <mark>FALSE</mark> otherwise.</td>
									</tr>
									<tr>
										<td class="monospace">outputType</td>
										<td>String / NULL</td>
										<td>Output can be set to <mark>'HTML'</mark>, <mark>'JSON'</mark> or <mark>NULL</mark>.</td>
									</tr>
									<tr>
										<td class="monospace">outputHeaders</td>
										<td>Array</td>
										<td>You can set HTML headers here.</td>
									</tr>
									<tr>
										<td class="monospace">outputHeadersSent</td>
										<td>Boolean</td>
										<td>This is set to <mark>TRUE</mark> if HTML headers already sent or <mark>FALSE</mark> otherwise.</td>
									</tr>
									<tr>
										<td class="monospace">outputStatusCode</td>
										<td>Integer</td>
										<td>This is set automatically if operation is successfull or if any errors happen. You can set your own HTTP status code here as well.</td>
									</tr>
								</tbody>
							</table>

						<h3>Methods</h3>
							<p>All the methods in Core can be used in a chain, see the example below:</p>
<pre>
$this->log('info', 'This is a test log.')->debug($_SERVER)->request('https://www.reddit.com/r/cats/.json')->debug();
</pre>

							<table class="table table-striped">
								<thead>
									<tr>
										<th>Method</th>
										<th>Description</th>
										<th>Return Value</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td class="monospace">setOutputType($outputType)</td>
										<td>Output can be set to <mark>'HTML'</mark>, <mark>'JSON'</mark> or <mark>NULL</mark>.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">setOutputHeaders($outputHeaders = array())</td>
										<td>You can set HTML headers here.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">setOutputStatusCode($outputStatusCode)</td>
										<td>This is set automatically if operation is successfull or if any errors happen. You can set your own HTTP status code here as well.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">output()</td>
										<td>This method causes the class to produce the output based on the <mark>outputType</mark></td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">log($level = 'debug', $message, array $context = array())</td>
										<td>This method is a wrapper for <a href="https://seldaek.github.io/monolog/">Monolog</a> and will produce an entry into the defualt log file.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">error($message, $outputStatusCode = 500)</td>
										<td>This method will throw an error and logs the error into the defualt log file. Calling this method also cause <mark>success</mark> to be <mark>FALSE</mark>.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">request($url, $method = 'GET', $data = '', array $headers = array())</td>
										<td>This is a wrapper method for php-curl, this allows you to call remote APIs and receive the response in OhCrud friendly way.</td>
										<td>OhCrud Object</td>
									</tr>
									<tr>
										<td class="monospace">debug($expression = null)</td>
										<td>If called without any parameters will output <mark>$this</mark> class. If an experssion is passed, this method will output that expression instead. Here an example of the <mark>debug()</mark> method: <br/> <img src="/assets/images/debug001.png" class="responsive" /></td>
										<td>OhCrud Object</td>
									</tr>
								</tbody>
							</table>

					</section>
					<div class="spacer"></div>

					<section id="section3_2">
						<h2 class="cl-black">Database Object</h2>

						<p>DB object is in charge of all the CRUD (<u>C</u>reate <u>R</u>ead <u>U</u>pdate <u>D</u>elete) work. This class inherits from Core, and comes with all the properties and methods that Core has.</p>

						<h3>Properties</h3>
						<p>Same as Core object</p>

						<h3>Methods</h3>
						<p>Same as Core object plus the following:</p>
						<table class="table table-striped">
							<thead>
								<tr>
									<th>Method</th>
									<th>Description</th>
									<th>Return Value</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td class="monospace">run($sql, $bind=array())</td>
									<td>This method will execute any SQL query agaist the database and will return the resulting dataset or a simple <mark>TRUE</mark> or <mark>FALSE</mark> if dataset is not present. While it is optional, you should use the <mark>$bind</mark> array to bind your data to your SQL placeholders. see example below:
<pre>
$this->run(
	'SELECT * FROM Users Where ID=:ID',
	[
		':ID' => 1
	]
);
</pre>
									</td>
									<td>OhCrud Object</td>
								</tr>
								<tr>
									<td class="monospace">create($table, $data=array())</td>
									<td>Use this method to insert a new record into the database, while it is optional, you should use the <mark>$bind</mark> array to bind your data to your SQL placeholders. see example below:
<pre>
$this->create(
	'Users',
	[
		'USERNAME' => 'admin',
		'PASSWORD' => password_hash(
			'admin', PASSWORD_BCRYPT, [
				'salt' => __OHCRUD_SECRET__,
				'cost' => 10
				]
			),
		'FIRSTNAME' => 'admin',
		'LASTNAME' => 'admin',
		'GROUP' => 1,
		'PERMISSIONS' => 1,
		'STATUS' => 1
	]
);
</pre>

									</td>
									<td>OhCrud Object</td>
								</tr>
								<tr>
									<td class="monospace">read($table, $where="", $bind=array(), $fields="*")</td>
									<td>Use this method to read records from database, while it is optional, you should use the <mark>$bind</mark> array to bind your data to your SQL placeholders. see example below:
<pre>
$this->read(
	'Users',
	'ID=:ID',
	[
		':ID' => 1,
	],
	'ID, USERNAME, FIRSTNAME, LASTNAME'
);
</pre>
									</td>
									<td>OhCrud Object</td>
								</tr>
								<tr>
									<td class="monospace">update($table, $data, $where, $bind=array())</td>
									<td>Use this method to update records in database, while it is optional, you should use the <mark>$bind</mark> array to bind your data to your SQL placeholders. see example below:
<pre>
$this->update(
	'Users',
	[
		'FIRSTNAME' => 'JOE',
		'LASTNAME' => 'COOl'
	],
	'ID=:ID',
	[
		':ID' => 1,
	]
);
</pre>

									</td>
									<td>OhCrud Object</td>
								</tr>
								<tr>
									<td class="monospace">delete($table, $where, $bind=array())</td>
									<td>
										Use this method to delete records from database, while it is optional, you should use the <mark>$bind</mark> array to bind your data to your SQL placeholders. see example below:
<pre>
$this->delete(
	"Users",
	"ID=:ID",
	[
		':ID' => 1,
	]
);
</pre>
									</td>
									<td>OhCrud Object</td>
								</tr>
								<tr>
									<td class="monospace">first()</td>
									<td>This method returns the first element of the <mark>data</mark> property. This method will terminate a method chain. See example below:
<pre>
$this->run('SELECT * FROM Users')->first();
</pre>
									</td>
									<td>Object (This method will return the fisrt element of the <mark>data</mark> property.</td>
								</tr>
								</tbody>
							</table>

					</section>
					<div class="spacer"></div>

					<section id="section3_3">
						<h2 class="cl-black">Router Object</h2>
						<p>Router object is your interface to the outside world, it will take a <u>path</u> which can be a <u>URI</u> or a <u>console argument</u> and will call upon the appropriate class and method to handle the request.<p>
						<p>To accomplish this task Router will look at the <mark>__OHCRUD_ENDPOINTS__</mark> and will call the class and method based on the defined name space, if the path was not defined in <mark>__OHCRUD_ENDPOINTS__</mark> then Router will look at <mark>__OHCRUD_DEFAULT_PATH_HANDLER__</mark> and will route the request to the <mark>defaultPathHandler</mark> method of the class defined here.</p>
						<p>If Router fails to find a path after trying the steps above, it will return a 404 error.</p>
						<p>Becasue router is matching paths to namespaces, it is very fast and you can change your endpoints at any time or redirect them to new namespaces to handle, this will make rolling out new versions of APIs super easy.</p>

						<h3>Permissions</h3>
						<p>Before calling objects and methods Router checks the target class for the public <mark>$permissions</mark> array property.

<pre>
namespace App\Models;

class Example extends \OhCrud\DB {

    public $permissions = [
        'object' => __OHCRUD_PERMISSION_ALL__,
        'exampleMethodA' => 2,
        'exampleMethodB' => 7
    ];
/*
the rest of the code for the Example class goes here...
*/
}
</pre>

					<p>If a user is present in the <mark>$_SESSION</mark>, Router will check that users <mark>PERMISSIONS</mark> value against the number assigned to the target method in <mark>$permissions</mark> array. if user's <mark>PERMISSIONS</mark> value <u>smaller than or equal to</u> the methods value it will grant access otherwise will return a 403 error.</p>
					<p>the <mark>'object'</mark> key in the <mark>$permissions</mark> array controls the global access to the object.</p>
					<p>To grant full access to a method or object without requiring user to login use <mark>__OHCRUD_PERMISSION_ALL__</mark> constant.</p>

					<p>When accessing a protected method, if user is not logged in, OhCrud will ask for the login credentians via basic authentication.</p>

					</section>
					<div class="spacer"></div>

					<section id="section3_4">
						<h2 class="cl-black">Users Object</h2>

						<p>Users object is the OhCrud's way of handling users and permissions, if <mark>__OHCRUD_DEBUG_MODE__</mark> is set to <mark>TRUE</mark>, OhCrud will create a Users table and will insert a defualt admin user into it as the starting point.</p>

						<h3>OhCrud default username and password</h3>
<pre>
Username : admin
Password : admin
</pre>

						<h3>Properties</h3>
						<p>Same as DB object</p>

						<h3>Methods</h3>
						<p>Same as DB object plus the following:</p>
						<table class="table table-striped">
							<thead>
								<tr>
									<th>Method</th>
									<th>Description</th>
									<th>Return Value</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td class="monospace">login($username, $password)</td>
									<td>This method will attempt to authenticate the user. If authentication is successfull results are stored in <mark>$_SESSION['User']</mark>.</td>
									<td>Boolean (TRUE on success, FALSE on failure)</td>
								</tr>
								<tr>
									<td class="monospace">logout()</td>
									<td>This will log out the user and remove the <mark>$_SESSION['User']</mark> value.</td>
									<td>TRUE</td>
								</tr>
							</tbody>
						</table>

					</section>


				</div>
			</div>

		</section>
		<div class="spacer"></div>
		<!-- -------------------------------------------------------------------------------- -->

		<section id="section4">

			<div class="row">
				<div class="col-md-12 left-align">
					<h2 class="cl-black">Errors &amp; Logging</h2>

					<p>OhCrud objects inherit from Core object, which means they all have a <mark>error($message, $outputStatusCode = 500)</mark> and <mark>log($level = 'debug', $message, array $context = array())</mark> method. Use this method to throw errors and set the HTTP status code.</p>
					<p>Database object (DB) will call the <mark>error</mark> method when a PDO exception occurs.</p>

					<p>OhCrud uses <a href="https://github.com/Seldaek/monolog">Monolog</a> liberary to handle logs, the <mark>log</mark> method in Core is a wrapper for Monolog. Use this method to record PSR-3 compliant log messages. The error method will also record a log.</p>
					<p>In OhCrud logs are fomatted like the examples below (output is trimmed to fit in this documentation page) :</p>

<pre>
[2017-07-25 15:01:16] OHCRUD.WARNING:
Login attempt was not successful
{"ID":"1","USERNAME":"admin","FIRSTNAME":"admin","LASTNAME":"admin","GROUP":"1",...
----------------------------------------
[2017-07-25 15:21:33] OHCRUD.ERROR:
SQLSTATE[HY000]: General error: 1 no such table: SomeTable
[{"file":"/var/www/ohcrud/ohcrud/DB.php","line":74,"function":"error","class":"O...
----------------------------------------
[2017-07-25 15:37:09] OHCRUD.ERROR:
I'm sorry Dave, I'm afraid I can't do that.
[{"file":"/var/www/ohcrud/ohcrud/Router.php","line":141,"function":"error","clas...
----------------------------------------
</pre>

				</div>
			</div>

		</section>
		<div class="spacer"></div>
		<!-- -------------------------------------------------------------------------------- -->

		<section id="section5">

			<div class="row">
				<div class="col-md-12 left-align">
					<h2 class="cl-black">Command Line Interface</h2>
					<p>You can call OhCrud paths and endpoints from your server's command line. When calling an endpoint from command line OhCrud will bypass the permissions array completely. If the otput type is not defined, OhCrud will print a debug output in the console. See example output below:</p>
<pre>
php path_to/index.php "/endpont/example/"

<img src="/assets/images/debug002.png" class="responsive" />
</pre>

				</div>
			</div>

		</section>
		<div class="spacer"></div>
		<!-- -------------------------------------------------------------------------------- -->

	</div>
</div>