<?php
    $content->theme = 'default';
    $content->layout = 'plain';
?>
<div class="col col-30 page center-vh">

    <form id="ohcrud-login" name="ohcrud-login">
        <h2>Please sign in</h2>
        <br>
        <div class="alert hidden"></div>
        <input type="text" placeholder="Username" name="USERNAME">
        <input type="password" placeholder="Password" name="PASSWORD">
        <input type="hidden" name="REDIRECT" value="<?= $_REQUEST['redirect'] ?? '' ?>">
        <input type="hidden" name="CSRF" value="<?= $this->CSRF() ?>">
        <br>
        <button type="submit" class="btn btn-primary" id="ohcrud-login-login">Login</button>
    </form>

</div>