<?php
    $content->theme = 'default';
    $content->layout = 'plain';
?>
<div class="col col-30 page center-vh">

    <form id="ohcrud-totp" name="ohcrud-totp">
        <h2>TOTP</h2>
        <p>Get the authentication code from the two-factor authentication app on your device.</p>
        <br>
        <div class="alert hidden"></div>
        <input type="text" placeholder="Authentication Code" name="TOTP_CODE">
        <input type="hidden" name="REDIRECT" value="<?= $_REQUEST['redirect'] ?? '' ?>">
        <input type="hidden" name="CSRF" value="<?= $this->CSRF() ?>">
        <br>
        <button type="submit" class="btn btn-primary" id="ohcrud-totp-login">Login</button>
    </form>

</div>