<?php
    // Prevent direct access to this class.
    if (isset($GLOBALS['OHCRUD']) == false) { die(); }

    // Check if user is logged in and has admin permissions
    if(isset($_SESSION['User']) == false || $_SESSION['User']->PERMISSIONS !== 1) {
        $this->redirect('/?action=login&redirect=/?action=edit');
        exit();
    }
?>

<input type="hidden" id="currentTHEME" value="{{CMS:THEME}}" />
<input type="hidden" id="currentLAYOUT" value="{{CMS:LAYOUT}}" />
<input type="hidden" id="currentSTATUS" value="{{CMS:STATUS}}" />
<input type="FILE" id="FILE" multiple style="display: none;" />

<div class="grid grid-gap grid-cols-1 medium-grid-cols-4 margin-top">

    <div class="list list-strong-ios list-dividers-ios inset-ios no-margin-vertical">
        <ul>
            <li class="item-content item-input">
                <div class="item-inner">
                <div class="item-title item-label">Title</div>
                <div class="item-input-wrap">
                    <input type="text" id="TITLE" name="TITLE" value="{{CMS:TITLE}}" maxlength="100" required validate pattern="[a-zA-Z0-9\- ]{3,100}" data-error-message="Page title must be alphanumeric.">
                    <span class="input-clear-button"></span>
                </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="list list-strong-ios list-dividers-ios inset-ios no-margin-vertical">
        <ul>
            <li class="item-content item-input">
                <div class="item-inner">
                <div class="item-title item-label">Theme</div>
                <div class="item-input-wrap input-dropdown-wrap">
                    <select id="THEME" name="THEME">
                    </select>
                </div>
            </li>
        </ul>
    </div>

    <div class="list list-strong-ios list-dividers-ios inset-ios no-margin-vertical">
        <ul>
            <li class="item-content item-input">
                <div class="item-inner">
                <div class="item-title item-label">Layout</div>
                <div class="item-input-wrap input-dropdown-wrap">
                    <select id="LAYOUT" name="LAYOUT">
                    </select>
                </div>
            </li>
        </ul>
    </div>

    <div class="list list-strong-ios list-dividers-ios inset-ios no-margin-vertical">
        <ul>
            <li class="item-content item-input">
                <div class="item-inner">
                <div class="item-title item-label">Status</div>
                <div class="item-input-wrap input-dropdown-wrap">
                    <select id="STATUS" name="STATUS">
                        <option value="2">Draft</option>
                        <option value="1">Published</option>
                        <option value="0">Deleted</option>
                    </select>
                </div>
            </li>
        </ul>
    </div>

</div>

<div class="card">
    <div class="card-content">
        <textarea id="TEXT" name="TEXT">{{CMS:CONTENT-TEXT}}</textarea>
    </div>
</div>

<div class="grid grid-gap grid-cols-1 medium-grid-cols-4 margin-top margin-bottom margin-horizontal">
    <button id="btnCMSSave" class="button button-fill">SAVE</button>
    <button id="btnCMSCancel" class="button button-outline">CANCEL</button>
    <div></div>
    <button id="btnCMSDeleteRestore" class="button color-red button-fill" data-is-deleted="{{CMS-IS-DELETED}}">DELETE</button>
</div>
