<div class="center-vh">
    <h1>Oh CRUD! You just got 404'd.</h1>
    <p>The page you requested at: <b><?= $path ?></b> could not be found.</p>
    <p>Use your browser's <b>Back</b> button to navigate to the page you have previously come from, or you could edit this page by pressing the edit button.</p>
    <br/>
    <a class="btn btn-primary external" href="/">Home</a>
    <a class="btn external" href="<?= isset($_SESSION['User']) ? $path . '?action=edit' : '/login/?redirect=' . $path . '?action=edit' ?>">Edit</a>
</div>