<input type="file" id="ohcrud-file" multiple style="display: none;" />
<div class="alert hidden"></div>
<form id="ohcrud-editor">
    <input type="hidden" id="url" name="URL" value="{{CMS:PATH}}" />
    <input type="hidden" id="current-theme" value="{{CMS:THEME}}" />
    <input type="hidden" id="current-layout" value="{{CMS:LAYOUT}}" />

    <div class="ohcrud-100">
        <div class="ohcrud-50">
            <input type="text" id="title" name="TITLE" value="{{CMS:TITLE}}" />
        </div>
        <div class="ohcrud-25 padding-left">
            <select id="theme" name="THEME"></select>
        </div>
        <div class="ohcrud-25 padding-left">
            <select id="layout" name="LAYOUT"></select>
        </div>
    </div>

    <textarea id="editor-text" name="TEXT">{{CMS:CONTENT-TEXT}}</textarea>
    <hr/>
    <button type="button" class="btn btn-primary" id="ohcrud-editor-save">Save</button>
    <button type="button" class="btn btn-secondary" id="ohcrud-editor-cancel">Cancel</button>
    <button type="button" class="btn btn-danger float-right" id="ohcrud-editor-delete-restore" data-is-deleted="{{CMS-IS-DELETED}}">...</button>
</form>