<input type="hidden" id="TABLE" name="TABLE" value="Files" />
<input type="hidden" id="PAGE_CURRENT" name="PAGE_CURRENT" value="1" />
<input type="FILE" id="FILE" multiple style="display: none;" />

<div class="card data-table data-table-init">
    <div class="card-header">
        <div class="data-table-title">Files</div>
        <div class="data-table-actions">
            <a id="btnTableView" class="link icon-only" data-link="?action=tables&table=Files&page=1">
                <i class="icon f7-icons">table</i>
            </a>
            <a id="btnUploadFile" class="link icon-only">
                <i class="icon f7-icons">arrow_up_square</i>
            </a>
        </div>
    </div>

    <div class="fileCards grid xsmall-grid-cols-1 small-grid-cols-2 medium-grid-cols-3 large-grid-cols-4 xlarge-grid-cols-5 xxlarge-grid-cols-6 xxxlarge-grid-cols-7">
    </div>

    <div class="data-table-footer">
        <div class="data-table-rows-select">Per page:
            <div class="input input-dropdown">
                <select id="LIMIT" name="LIMIT">
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </div>
        </div>
        <div class="data-table-pagination">
            <span ID="RECORDS_DISPLAYED" class="data-table-pagination-label">...</span>
            <div class="pagination-wrapper">
                <a ID="btnPagePrevious" href="#" class="link disabled">
                    <i class="icon icon-prev color-gray"></i>
                </a>
                <a ID="btnPageNext" href="#" class="link">
                    <i class="icon icon-next color-gray"></i>
                </a>
            </div>
        </div>
    </div>

</div>
