<?php
    $content->theme = 'default';
    $content->layout = 'plain';
?>
<div class="col col-30 page center-vh">

    <div class="alert hidden"></div>
    <form id="ohcrud-login" name="ohcrud-login">
        <h2>Please sign in</h2>
        <br>
        <input type="text" placeholder="Username" name="USERNAME">
        <input type="password" placeholder="Password" name="PASSWORD">
        <input type="hidden" name="REDIRECT" value="<?= $_REQUEST['redirect'] ?? '' ?>">
        <input type="hidden" name="CSRF" value="<?= $this->CSRF() ?>">
        <br>
        <button type="submit" class="btn btn-primary" id="ohcrud-login-login">Login</button>
        <a class="btn btn-default" href="<?= parse_url($_REQUEST['redirect'] ?? '/', PHP_URL_PATH) ?>">Cancel</a>
    </form>

    <form id="ohcrud-totp" name="ohcrud-totp" class="hidden">
        <h2>Please sign in</h2>
        <p>Get the authentication code from the two-factor authentication app on your device.</p>
        <br>
        <input type="text" placeholder="TOTP Code" name="TOTP_CODE">
        <input type="hidden" name="REDIRECT" value="<?= $_REQUEST['redirect'] ?? '' ?>">
        <input type="hidden" name="CSRF" value="<?= $this->CSRF() ?>">
        <br>
        <button type="submit" class="btn btn-primary" id="ohcrud-login-totp">Verify</button>
        <a class="btn btn-default" href="<?= parse_url($_REQUEST['redirect'] ?? '/', PHP_URL_PATH) ?>">Cancel</a>
    </form>

</div>