<?php
// Sanitize the table name
$table = preg_replace('/[^a-zA-Z0-9_]/', '', $this->purifier->purify($_REQUEST['table'] ?? ''));
?>

<input type="hidden" id="TABLE" name="TABLE" value="<?= $table ?>" />
<input type="hidden" id="PAGE_CURRENT" name="PAGE_CURRENT" value="1" />

<div class="card data-table data-table-init">
    <div class="card-header">
        <div class="data-table-title"><?= $table ?? '' ?></div>
        <div class="data-table-actions">

            <a class="link icon-only">
                <i class="icon f7-icons">ellipsis_circle</i>
            </a>
        </div>
    </div>
    <table>
        <thead class="tableHeader">
        </thead>
        <tbody class="tableBody">
        </tbody>
    </table>
    <div class="data-table-footer">
        <div class="data-table-rows-select">Per page:
            <div class="input input-dropdown">
                <select id="LIMIT" name="LIMIT">
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </div>
        </div>
        <div class="data-table-pagination">
            <span ID="RECORDS_DISPLAYED" class="data-table-pagination-label">...</span>
            <a ID="btnPagePrevious" href="#" class="link disabled">
                <i class="icon icon-prev color-gray"></i>
            </a>
            <a ID="btnPageNext" href="#" class="link">
                <i class="icon icon-next color-gray"></i>
            </a>
        </div>
    </div>
</div>