<div class="card data-table">
    <div class="card-header">
        <div class="data-table-title">Nutrition</div>
        <div class="data-table-actions">

            <a class="link icon-only">
                <i class="icon f7-icons">ellipsis_circle</i>
            </a>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th class="checkbox-cell">
                    <label class="checkbox">
                        <input type="checkbox" /><i class="icon-checkbox"></i>
                    </label>
                </th>
                <th class="label-cell">Dessert (100g serving)</th>
                <th class="numeric-cell">Calories</th>
                <th class="numeric-cell">Fat (g)</th>
                <th class="numeric-cell">Carbs</th>
                <th class="numeric-cell">Protein (g)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="checkbox-cell">
                    <label class="checkbox">
                        <input type="checkbox" /><i class="icon-checkbox"></i>
                    </label>
                </td>
                <td class="label-cell">Frozen yogurt</td>
                <td class="numeric-cell">159</td>
                <td class="numeric-cell">6.0</td>
                <td class="numeric-cell">24</td>
                <td class="numeric-cell">4.0</td>
                <td class="actions-cell">
                    <a class="link icon-only"><i class="icon f7-icons">square_pencil</i></a>
                    <a class="link icon-only"><i class="icon f7-icons">trash</i></a>
                </td>
            </tr>
            <tr>
                <td class="checkbox-cell">
                    <label class="checkbox">
                        <input type="checkbox" /><i class="icon-checkbox"></i>
                    </label>
                </td>
                <td class="label-cell">Ice cream sandwich</td>
                <td class="numeric-cell">237</td>
                <td class="numeric-cell">9.0</td>
                <td class="numeric-cell">37</td>
                <td class="numeric-cell">4.4</td>
                <td class="actions-cell">
                    <a class="link icon-only"><i class="icon f7-icons">square_pencil</i></a>
                    <a class="link icon-only"><i class="icon f7-icons">trash</i></a>
                </td>
            </tr>
            <tr>
                <td class="checkbox-cell">
                    <label class="checkbox">
                        <input type="checkbox" /><i class="icon-checkbox"></i>
                    </label>
                </td>
                <td class="label-cell">Eclair</td>
                <td class="numeric-cell">262</td>
                <td class="numeric-cell">16.0</td>
                <td class="numeric-cell">24</td>
                <td class="numeric-cell">6.0</td>
                <td class="actions-cell">
                    <a class="link icon-only"><i class="icon f7-icons">square_pencil</i></a>
                    <a class="link icon-only"><i class="icon f7-icons">trash</i></a>
                </td>
            </tr>
            <tr>
                <td class="checkbox-cell">
                    <label class="checkbox">
                        <input type="checkbox" /><i class="icon-checkbox"></i>
                    </label>
                </td>
                <td class="label-cell">Cupcake</td>
                <td class="numeric-cell">305</td>
                <td class="numeric-cell">3.7</td>
                <td class="numeric-cell">67</td>
                <td class="numeric-cell">4.3</td>
                <td class="actions-cell">
                    <a class="link icon-only"><i class="icon f7-icons">square_pencil</i></a>
                    <a class="link icon-only"><i class="icon f7-icons">trash</i></a>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="data-table-footer">
        <div class="data-table-rows-select">Per page:<div class="input input-dropdown">
                <select>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="25">25</option>
                    <option value="all">All</option>
                </select>
            </div>
        </div>
        <div class="data-table-pagination">
            <span class="data-table-pagination-label">1-5 of 10</span>
            <a href="#" class="link disabled">
                <i class="icon icon-prev color-gray"></i>
            </a>
            <a href="#" class="link">
                <i class="icon icon-next color-gray"></i>
            </a>
        </div>
    </div>
</div>